elasticsearch:
  image: deviantony/elk-elasticsearch
  volumes: 
    - elasticsearch:/etc/elasticsearch/
  ports:
    - "9200:9200"
redis:
  image: library/redis
  ports:
  - "6379:6379"
logstash:
  image: deviantony/elk-logstash
  volumes:
    - logstash-conf:/etc/logstash/conf.d
  ports:
    - "5000:5000"  
  links:
    - elasticsearch
    - redis
kibana4:
  image: deviantony/elk-kibana
  ports:
    - "5601:5601"
  links:
    - elasticsearch
